# Generated by Django 5.0.3 on 2024-03-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chatTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ct_name", models.CharField(max_length=50, verbose_name="聊天主题名称")),
                ("create_time", models.DateTimeField(verbose_name="创建时间")),
                ("state", models.BooleanField(blank=True, verbose_name="状态")),
            ],
            options={
                "verbose_name": "聊天主题",
                "verbose_name_plural": "聊天主题",
            },
        ),
        migrations.CreateModel(
            name="knowledgeStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ks_name", models.CharField(max_length=50, verbose_name="知识库名")),
                ("create_time", models.DateTimeField(verbose_name="创建时间")),
                ("state", models.BooleanField(blank=True, verbose_name="状态")),
            ],
            options={
                "verbose_name": "知识库",
                "verbose_name_plural": "知识库",
            },
        ),
        migrations.CreateModel(
            name="chatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ch_name", models.CharField(max_length=5000, verbose_name="聊天记录")),
                ("state", models.BooleanField(blank=True, verbose_name="状态")),
                ("create_time", models.DateTimeField(verbose_name="发送/回复时间")),
                (
                    "ct_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QA.chattopic",
                        verbose_name="聊天主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天记录",
                "verbose_name_plural": "聊天记录",
            },
        ),
        migrations.CreateModel(
            name="DocStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_name", models.CharField(max_length=50, verbose_name="文件名称")),
                ("load_time", models.DateTimeField(verbose_name="加载时间")),
                ("state", models.BooleanField(blank=True, verbose_name="状态")),
                (
                    "ks_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QA.knowledgestore",
                        verbose_name="知识库名",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库文件",
                "verbose_name_plural": "知识库文件",
            },
        ),
    ]
