# Generated by Django 5.0.3 on 2024-03-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QA", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattopic",
            name="ct_session_id",
            field=models.CharField(max_length=50, null=True, verbose_name="主题检索id"),
        ),
    ]
