# Generated by Django 5.0.3 on 2024-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QA", "0002_chattopic_ct_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chathistory",
            old_name="ch_name",
            new_name="ch_content",
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="发送/回复时间"),
        ),
        migrations.AlterField(
            model_name="chattopic",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="docstore",
            name="load_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="加载时间"),
        ),
        migrations.AlterField(
            model_name="knowledgestore",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
    ]
