# Generated by Django 5.0.3 on 2024-03-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QA", "0003_rename_ch_name_chathistory_ch_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgestore",
            name="data_num",
            field=models.IntegerField(default=0, verbose_name="数据条目数"),
            preserve_default=False,
        ),
    ]
